### ISSUE TITLE
Anpassungen Reporting 2021

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#103]
Aktuell ist davon auszugehen, dass nachfolgende Anpassung im Hinblick auf das Reporting
2021 erfolgen muss. Eine verbindliche Zusage des BSV fehlt noch (August 2021):

* Es ist davon auszugehen, dass die FTE für das nächste Reporting-Jahr OHNE Honorarkräfte
angegeben werden müssen. Entsprechend muss die Programmierung des Outputs von
insieme desk für die beiden Felder «FTE angestellte MA insgesamt» und «FTE angestellte MA
Betrieb Art. 74 IVG» umprogrammiert werden.

insieme desk - insieme Schweiz: https://desk.insieme.ch/de/groups/1/time_record/2020/base_information

1. Angestellte MitarbeiterInnen. Zeiterfassung (in 100% Stellen) / Ganze
Organisation **PLUS Honorare; Ertrag FIBU (aus Kostenrechnung) dividiert durch 13**0 
-> Honorarkomponente entfernen
2. Angestellte MitarbeiterInnen. Zeiterfassung (in 100% Stellen) / Art. 74 betreffend
**PLUS Honorare; Aufwand/Total (aus Kostenrechnung) dividiert durch 130** 
-> Honorarkomponente entfernen
3. Ehrenamtliche Arbeit mit Leistungsnachweis (in 100% Stellen) / Ganze
Organisation -> unverändert belassen
4.  Ehrenamtliche Arbeit mit Leistungsnachweis (in 100% Stellen) / Art. 74 betreffen 
-> unverändert belassen

# Tech-Spec
- https://github.com/hitobito/hitobito_insieme/blob/a03146008c2b64ccebe76f87454fd4e5baf628a9/app/domain/vertragsperioden/dispatcher.rb
- https://github.com/hitobito/hitobito_insieme/tree/master/spec/vp2020

# ToDo

- [x] Neue Vetragsperiode 2021 erstellen
- [x] obige Regeln entsprechend umsetzen
- [x] Tests für die neuen Regeln in spec/vp2021 erstellen (ggf. Struktur von vp2020 kopieren)

**Comment by kronn** [comment]
Die genannten Basisinformationen sind manuell eingetragene Werte, nicht Berechnungen. Ist hier die Reporting-Übersicht gemeint?
