### ISSUE TITLE
ADDRESS: Viele Adressen als invalid getagt

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#117]
Gemäss Kunde sind sehr viele (alle?) Adressen mit "invalid" getagt. 

## Ansätze

- die Tags werden nicht richtig gelöscht (Siehe https://github.com/hitobito/hitobito/issues/1431)
	- Die Prüfung hat stattgefunden, bevor das Verzeichnis komplett da war
- das Adressverzeichnis ist nicht korrekt vorhanden
	- Der erste Import des Verzeichnisses ist auf 6 Monate in der Zukunft gesetzt
	- die erste Validierung gegen das Adressverzeichnis ist auf 1 Tag in der Zukunft gesetzt
- Ähnlichkeit zu https://help.puzzle.ch/#ticket/zoom/3314 ?
- Job: `Address::CheckValidityJob`

## ToDo

- [x] Prüfen, ob Verzeichnis vorhanden ist
- [x] Prüfen, ob Adressen richtig im Sphinx vorhanden sind (Adressvervollständigung testen)
- [ ] Prüfen, ob Tags richtig gelöscht werden können
- [x] ggf. entsprechende Tags in der DB löschen und alles neu prüfen lassen
- [ ] ggf. notwendige Anpassungen machen, damit das nicht mehr so leicht passieren kann
