### ISSUE TITLE
VP2021: Vertragsperiode entfernen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_insieme#120]
Es sind mehrere Anpassungen erwünscht, die insgesamt durch das Entfernen der Vertragsperiode 2021 gelöst werden können:

## Tech-Spec

- Die Zeile «Summe der DB4 2020-2020» ist obsolet. Es gibt keine Vertragsperiode 2020-2020 sondern nur 15-19 20-23.  Stattdessen sollte der Betrag der Zeile mit «2021-2023» addiert werden und als «2020-2023» angezeigt werden. Somit würde jeweils eine Zeile weniger angezeigt.
- Das BSV hat die angesagte Änderung nun doch nicht vorgenommen. Wir würden die Berechnungen gerne belassen wie vor der Änderung. 
- IV-Finanzierungsgrad: Analog zu Anpassung 4 erscheint die Zeile «2020-2020». Diese Zeile sollte nicht angezeigt werden und stattdessen bei 2020-2023 addiert werden.

## ToDo

- [ ] Revert des Feature-Branches prüfen
- [ ] Alternativ: VP2021 aus `app` und `spec` löschen
- [ ] CHANGELOG prüfen und ggf anpassen
- [ ] `Vertragsperiode::Dispatcher` prüfen und ggf. anpassen
