### ISSUE TITLE
CONTROLLING: IV-Finanzierungsgrad nachbessern

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_insieme#121]
Es sind noch ein paar Anpassungen am IV-Finanzierungsgrad gewünscht

## Berechung

Die dargestellten Beträge werden wie folgt berechnet: 

```
SummeÜberJahre(Total IV-Beitrag)/SummeÜberJahre(Gesamtkosten Betrieb Art74)
```

Stattdessen würden wir Sie gerne wie folgt berechnet haben: 

```
SummeÜberJahre(IV-Finanzierungsgrade des jeweiligen Jahres)/Anzahl Jahre
```

wobei

```
IV-Finanzierungsgrad des jeweiligen Jahres = Total IV-Beitrag/ Gesamtkosten Betrieb Art74
```

Anzahl Jahre wäre mit der Dauer der VP identisch: 3 in VP15-19 bzw. 4 in VP 20-23.

## Darstellung

Die Zeile «IV-Finanzierungsgrad 2015 – AktuellesReportingJahr» fehlt noch an erster Stelle. Zusätzlich wäre es für die einfachere Interpretation der User für uns angenehm, wenn «AktuellesReportingJahr» als Jahreszahl erscheinen würde. (=Default Reporting Jahr) 

https://insieme.puzzle.ch/de/global_value/edit

Wenn wir statt «aktueller IV Finanzierungsgrad» «IV Finanzierungsgrad [AktuellesReportingJahr]» darstellen könnten, wäre das ebenfalls hilfreich.
Zeilen:
Durchschnittlicher IV Finanzierungsgrad 2015- [aktuelles Jahr]
Durchschnittlicher IV Finanzierungsgrad 2015-2019
Durchschnittlicher IV Finanzierungsgrad 2020-2023
IV Finanzierungsgrad [aktuelles Jahr]

## ToDo

- [x] Berechnung prüfen und ggf anpassen
- [x] Specs anpassen
- [x] Zeile "IV-Finanzierungsgrad bis `@current_year`" hinzufügen
- [x] Anpassung der Darstellung prüfen
