### ISSUE TITLE
PEOPLE: Neue Stichwörter

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#124]
Als rechnungsstellende oder personenmutierende Person bei der insieme Schweiz wünsche ich mir weitere Stichwörter für die Telefonnummern, Rechnungs-, Korrespondenz- und E-Mail-Adressen. Um für die Nummern und Adressen eine passendere Bezeichnung zu haben. 
Neu sollen folgende Stichwörter verfügbar sein: Privat, Mobil, Arbeit, Vater, Mutter, Beistand, Wohngruppe, Wohnheim, FAX, Andere.
Zu beachten ist, dass die Stichwörter "Mobil" und "FAX" lediglich für die Telefonnummern verfügbar sein sollen. Die restlichen Stichwörter sind auch für Rechnungs-, Korresponenz-, und E-Mail-Adressen verfügbar.

# Mockup

![image](https://user-images.githubusercontent.com/69250571/201648329-4a89b70a-57ae-4f15-8a4d-aaddcf373a40.png)

# Tech-Spec

- Stichwörter ergänzen/anpassen/neu: Privat, Mobil, Arbeit, Vater, Mutter, Beistand, Wohngruppe, Wohnheim, FAX, Andere
- Stichwörter für Telefonnummern, Rechnungs-, Korrespondenz- und E-Mail-Adressen
- Mobil und FAX nur für Telefonnummern
- Stichwörter sind `label` und `predefined_labels` im Code
- predefined labels sind in `config/settings.yml` definiert und müssen im Wagon ergänzt oder überschrieben werden.

# ToDo

- [ ] Verhalten für existierende Labels definieren
- [x] Neue Stichwörter für Telefonnummern
- [x] Neue Stichwörter für Rechnungsadressen
- [x] Neue Stichwörter für Korrespondenzadressen
- [x] Neue Stichwörter für E-Mail-Adressen
- [x] Eingabefeld für Stichwörter bei weiteren E-Mail-Adressen zu Dropdown machen
- [x] Dropdown für Stichwörter bei Rechnungsadressen hinzufügen
- [x] Dropdown für Stichwörter bei Korrespondenzadressen hinzufügen
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
