### ISSUE TITLE
Berechnungen FTE

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#125]
Als rechnungsstellende Person bei der Insieme möchte ich, dass die angepassten Berechnungen der FTE im Export eingepflegt werden. Die Berechnungen wurden im Januar bereits angepasst. Aufgrund eines Missverständnisses geschah das aber bei der Zeiterfassungsansicht und wurde anschliessend wieder rückgängig gemacht #103. Die neuen Berechtigungen gelten erst für die Vertragsperiode ab dem 01.01.2022. Für Vertragsperioden vor dem 01.01.2022 gilt weiterhin die bis anhin verwendeten Berechnungen.

Neu soll die im Januar angepasste Berechnungen der FTE im Export eingepflegt werden.

# Tech-Spec

- Berechnungen FTE gemäss #103 
- PR #115 beachten
- Tests für die neuen Regeln in spec/vp2021 erstellen (ggf. Struktur von vp2020 kopieren)

# ToDo

- [x] Vertragsperiode zu `FeaturePeriod` umbenennen
- [x] FP2022 anlegen (`rake vp:new[2022]`)
- [x] Anpassungen an Honorarkomponente (siehe #103) vornehmen
- [x] Tests für die neuen Regeln in spec/vp2021 erstellen
- [x] Anpassungen an Export vornehmen
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
