### ISSUE TITLE
INVOICES: Anpassung Zeiterfassung für Grundlagenarbeit zu Kursen und Treffpunkten

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#127]
Als Person, die das Reporting im Insieme Desk überblickt, möchte ich, dass die Positionen für die Zeiterfassung von Angestellten und Ehrenamtlichen mit und ohne Ausweis angepasst werden damit die geleisteten Stunden feingranularer ausgewiesen werden können.

Neu sollen für die "Grundlagenarbeit zu Kursen" und für die "Grundlagenarbeit zu Treffpunkten" separate Positionen für die Zeiterfassung existieren. Die "Grundlagenarbeit zu Kursen" bleibt die erste Buchungsposition. Die "Grundlagenarbeit zu Treffpunkten" rutscht auf die zweitletzte Stelle, direkt vor die Position "Treffpunkte".

Neu sollen die Stunden der Position "Grundlagenarbeit zu Kursen" auf den Kostenträger "LUFEB" verteilt werden.
Die Stunden der Position "Grundlagenarbeit zu Treffpunkten" sollen auf den Kostenträger "Treffpunkte" verteilt werden.

# Mockup
![image](https://user-images.githubusercontent.com/69250571/204137133-ade9fc8f-5415-4b26-8f76-410cb03cef21.png)

# Tech-Spec

- Buchungsposition für "Grundlagenarbeit zu Kursen und Treffpunkten" wird aufgeteilt in zwei neue Positionen
- Code in FP2022 anlegen
- Es müssen keine neuen Kostenträger erstellt werden. Lediglich die Verteilung der Stunden auf die bestehenden Kostenträger und die Buchungspositionen gemäss #127 verändern sich.

# ToDo

- [x] Migration: `add_column :time_records, :treffpunkte_grundlagen, :integer`
- [x] Buchungsposition für "Grundlagenarbeit zu Kursen und Treffpunkten" zu "Grundlagenarbeit zu Kursen" (`kurse_grundlagen`) umbenennen
- [x] Neue Buchungsposition für "Grundlagenarbeit zu Treffpunkten" (`treffpunkte_grundlagen`) auf zweitletzter Position
- [x] nach Verwendung von `kurse_grundlagen` suchen und Aufteilung dort ggf. anpassen (:warning: inhaltlich mitdenken, siehe oben!)
	- [x] Summierung in `FP2022::TimeRecord::Calculation#total_courses` anpassen
	- [x] Stunden auf "Grundlagenarbeit zu Kursen" werden zu "LUFEB" verteilt
	- [x] Stunden auf "Grundlagenarbeit zu Treffpunkten" werden zu  "Treffpunkte" verteilt
- [ ] Specs schreiben und anpassen
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
