### ISSUE TITLE
INVOICES: Anpassung Schlüssel Kostenrechnung

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#128]
Als Person, welche bei der Insieme für die Finanzen verantwortlich ist, möchte ich, dass entsprechend den Anpassungen der Buchungspositionen #127 auch der Schlüssel für die Kostenrechnung angepasst wird. Dies soll sicherstellen, dass die verschiedenen Buchungspositionen auch auf die entsprechenden Kostenträger verteilt werden.
Neu sollen die Stunden der Position "Grundlagenarbeit zu Kursen" auf den Kostenträger "LUFEB" verteilt werden. Die Stunden der Position "Grundlagenarbeit zu Treffpunkten" sollen auf den Kostenträger "Treffpunkte" verteilt werden.

# Tech-Spec

- Es müssen keine neuen Kostenträger erstellt werden. Lediglich die Verteilung der Stunden auf die bestehenden Kostenträger und die Buchungspositionen gemäss #127 verändern sich.

# ToDo

- [ ] Stunden auf "Grundlagenarbeit zu Kursen" werden zu "LUFEB" verteilt
- [ ] Stunden auf "Grundlagenarbeit zu Treffpunkten" werden zu  "Treffpunkte" verteilt
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kronn** [comment]
Ich habe das Ticket mit #127 zusammengelegt, es bringt wenig Mehrwert, das in diesem Fall zu trennen.
