### ISSUE TITLE
EVENTS: Meldung bei überbuchten Kurs

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#129]
Beim **manuellen Hinzufügen** einer Person zu einem bereits überbuchten Kurs, erscheint die Meldung, dass die Person auf der Warteliste landet. Tatsächlich wird diese aber direkt als Teilnehmende Person hinzugefügt.

Als Kursleiter:in möchte ich, dass die Meldung angepasst wird, da das Verhalten so korrekt ist.

Neu soll die Meldung, dass die Person auf der Warteliste landet beim manuellen Hinzufügen von Personen zu einem Kurs ersetzt werden. In der neuen Meldung soll mitgeteilt werden, dass die die Person als Teilnehmer:in dem Kurs hinzugefügt wurde.

# Tech-Spec

- Die Logik beim manuellen Hinzufügen von Personen zu Kursen ist korrekt.
- Es soll lediglich die Meldung, die dann erscheint angepasst werden.

# ToDo

- [ ] Neue Meldung verfassen und für manuelles Hinzufügen verwenden
- [ ] Alte Meldung bleibt bei normaler Anmeldung mit Warteliste bestehen
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] Kunde wegen Übersetzungen informieren
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by daniel-illi** [comment]
Ich kann das beschriebene Verhalten nicht reproduzieren. Wenn ich eine Person manuell einem überbuchten Kurs zuordne, dann kriege ich diese Meldung:

    "Teilnahme von [Vorname Name] in [Kursnummer] wurde erfolgreich erstellt. Bitte überprüfe die Kontaktdaten und passe diese gegebenenfalls an."
    
Z.B. in diesem Kurs: https://insieme.puzzle.ch/de/groups/1/events/4871
    
@mlue00 kannst du mir helfen das zu reproduzieren?
