### ISSUE TITLE
EVENTS: Tabansicht Kursübersicht

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#130]
Als Kursorganisator:in stelle ich fest, dass bei einigen Vereinen nicht alle Kurse in der Tabansicht angezeigt werden.

Es werden nur Kurse mit dem Startdatum bis zum 17.05.2022 aufgeführt. Ich möchte, dass auch Kurse mit späterem Startdatum angezeigt werden, damit die Übersicht eine vollständige Liste anzeigt.

Neu sollen in der Kursübersicht sämtliche Kurse aufgeführt werden.

# Tech-Spec

- Die Tabansicht scheint Kurse ab dem 17.05.2022 nicht mehr zu berücksichtigen.
- https://desk.insieme.ch/de/groups/316/events/4221
- Der Kurs wurde im Oktober in der Ansicht list_course angezeigt, aber auf dem Tab Course auf der Gruppe nicht.
- Vermutung: Es werden nur Kurse mit Beginn bis zum aktuellen Datum angezeigt

# ToDo

- [ ] In der Tabansicht der Kursübersicht werden alle Kurse angezeigt
- [ ] Model/View/Controller anpassen?
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by carlobeltrame** [comment]
Ich kann den Bug reproduzieren, wenn ich die bei insieme deployte Version von hitobito laufen lasse. Wenn ich aber stattdessen die aktuelle Version von hitobito laufen lasse, tritt es nicht mehr auf. Ich nehme an das wurde in #1853 gefixt. Es wird also mit dem nächsten Produktionsdeployment automatisch gefixt werden.
