### ISSUE TITLE
Sprachliche Anpassungen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#131]
Bei der Hitobito-Instanz der Insieme sind einige sprachliche Anpassungen angebracht.

Neu wird von "Personen mit Behinderung" und nicht mehr von "Behinderten" gesprochen.
Ebenfalls wird der Ausdruck "Mehrfachbehinderte" durch "Personen mit mehrfacher
Behinderung" ersetzt.

In diesem Issue soll lediglich die Übersetzung stattfinden.
Die visuelle Überprüfung wird durch den Kunden durchgeführt und anschliessend wird entscheiden ob weitere Anpassungen vorgenommen werden.

# ToDo

- [ ] "Behinderte" wurden zu "Personen mit Behinderung" umbenannt
- [ ] "Mehrfachbehinderte" wurden zu "Personen mit mehrfacher Behinderung"
- [ ] Webseite von Kunden visuell überprüfen lassen
- [ ] Kunde wegen Übersetzungen informieren
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by daniel-illi** [comment]
Wie soll "Geistig-/Lernbehinderte" angepasst werden? "Personen mit geistiger Behinderung/Lernbehinderung"?
