### ISSUE TITLE
INVOICES: Verhalten der Rechnungsadressen anpassen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#133]
Als rechnungsstellende Person bei der Insieme möchte ich, dass die Rechnungsadresse dynamisch anpassbar ist. Bei Vorhandensein der Rechnungsadresse soll auch diese verwendet werden können. Aktuell wird jeweils noch die Standard-Adresse als Rechnungs-Adresse eingetragen. Ziel ist es, dass die Rechnungen an die dafür vorgesehenen Adressen geschickt werden können.

Neu soll die Rechnungsadresse dynamisch anpassbar sein. Man kann also bei Vorhandensein der Rechnungsadresse diese verwenden. Auf dem PDF für die Ausdrucke soll ein Hinweis auf den "Leistungsbezüger" untergebracht werden.

# Tech-Spec

- Rechnungsadresse wird, wenn eine vorhanden ist, verwendet.
- Leistungsbezüger ausweisen, wenn abweichende Adresse verwendet wird.

# ToDo

- [ ] Core: `Person#address_for_invoice` hinzufügen und bei Rechnungen (`app/models/invoice.rb`) verwenden, weiterleiten auf `Person#address_for_letter`
- [ ] Wagon: `Person#address_for_invoice` erweitern
	- [ ] Rechnungsadresse allgemein wird, wenn vorhanden, verwendet.
- [ ] Hinweis auf "Leistungsbezüger" auf PDF, wenn Rechnungsadresse statt Standardadresse verwendet wird.
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
