### ISSUE TITLE
CONTROLLING: Export des Finanzierungsgrades

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#134]
Als finanzberechtigte Person bei der Insieme möchte ich, dass die finanziellen Kennzahlen der Vereine besser aufgeschlüsselt werden, damit man aussagekräftigere Daten betreffend dem Finanzierungsgrad erhält.

Neu soll der IV Finanzierungsgrad des aktuellen Jahres in den Export "Kennzahlen pro Verein" eingepflegt werden.

# Tech-Spec

-  "IV Finanzierungsgrad [aktuelles Jahr]" soll in folgenden Export integriert werden: «Kennzahlen pro Verein»

# ToDo

- [x] Specs anpassen
- [x] eventuell Datenklasse `FP2022::Statistics::GroupFigures` anpassen
- [x] Export `FP2022::Export::Tabular::Statistics::GroupFigures` anpassen
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
