### ISSUE TITLE
PEOPLE: 2FA enforcen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#135]
Es soll bei Gruppen mit kritischen Berechtigungen die Zwei-Faktor-Authentifizierung enforced werden.

Neu soll 2FA bei folgenden Gruppen enforced werden (alle Gruppen mit Rechten):

    * Dachverein
      * Dachverein
        * PräsidentIn: [:layer_read, :contact_data]
        * Vorstandsmitglied: [:layer_read]
        * Geschäftsführung: [:admin, :layer_and_below_full, :contact_data, :impersonation, :finance]
        * Sekretariat: [:layer_and_below_full, :contact_data]
        * Adressverwaltung: [:layer_and_below_full, :contact_data]
        * Controlling: [:admin, :layer_and_below_full, :contact_data]
        * Rechnungen: [:layer_and_below_read, :finance]
        * IT Support: [:admin, :layer_and_below_full, :impersonation]
      * Liste
        * Listenverwaltung: [:group_full]
      * Gremium
        * Leitung: [:group_full, :contact_data]
        * Mitglied: [:group_read]
    * Regionalverein
      * Regionalverein
        * PräsidentIn: [:layer_read, :contact_data]
        * Vorstandsmitglied: [:layer_read]
        * Geschäftsführung: [:layer_full, :contact_data]
        * Sekretariat: [:layer_full, :contact_data]
        * Adressverwaltung: [:layer_full, :contact_data]
        * Versandadresse: [:contact_data]
        * Rechnungsadresse: [:contact_data]
        * Controlling: [:contact_data]
        * Rechnungen: [:layer_and_below_read, :finance]
      * Liste
        * Listenverwaltung: [:group_full]
      * Gremium
        * Leitung: [:group_full, :contact_data]
        * Mitglied: [:group_read]
    * Externe Organisation
      * Externe Organisation
        * PräsidentIn: [:layer_read, :contact_data]
        * Vorstandsmitglied: [:layer_read]
        * Geschäftsführung: [:layer_full, :contact_data]
        * Sekretariat: [:layer_full, :contact_data]
        * Adressverwaltung: [:layer_full, :contact_data]
        * Versandadresse: [:contact_data]
        * Rechnungsadresse: [:contact_data]
        * Controlling: [:contact_data]
        * Rechnungen: [:layer_and_below_read, :finance]
      * Liste
        * Listenverwaltung: [:group_full]
      * Gremium
        * Leitung: [:group_full, :contact_data]
        * Mitglied: [:group_read]

# Tech-Spec

- 2FA für alle genannten enforced werden.
- In der jeweiligen Rollenklasse `self.two_factor_authentication_enforced = true` setzen

# ToDo

- [ ] 2FA für alle definierten Gruppen und Rollen enforced
- [ ] Specs schreiben und ggf. anpassen
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] 2FA für den hitobito/puzzle-Support User im Cryptopus hinterlegen
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
