### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_insieme#150]
Viele Personen welche sich bei Insieme einloggen kennen das System nur schlecht, verwenden dieses nur selten, und/oder sind eher Technik-unaffin. Um diesen Benutzern zu helfen soll bei der Insieme eine einfache Landing Page eingebaut werden, welche die Benutzer etwas lenken kann, damit sie die von ihnen benötigten Informationen einfacher finden.

Neu sollen Benutzer nach dem Einloggen bei Insieme nicht auf ihrem Profil landen, sondern auf einer Landing Page (Eigene Seite /Poppup, separates Tab, was am einfachsten geht). Diese Page soll einige fixe Informationen enthalten.

- Die Langind Page ist für alle Benutzer gleich
- Die Landing Page beinhaltet nur einen Fliesstext. Es muss möglich sein, Links zu externen Seiten in den Text einzubetten.
- Die Langing Page soll durch Administrationen auf dem Top-Layer verändert werden können.
- Übersetzungen zur Landing Page sollen ~~im Transifex~~ via CustomContents möglich sein. Die landing Page soll immer in der ausgewählen Sprache des Users angezeigt werden.
- Von der Landing Page muss ein Absprung zu einer externen, ungeschützten Internettseite von Insieme (Guide / Benutzeranleitung) möglich sein.

~~Alternative:
Wenn es viel günstiger ist, wäre alternativ auch ein neues Tab "Hilfe" vorstellbar, welches dann die Informationen und den Absprung zur Externen Seite enthält.~~

# Tech-Spec

- Umsetzung im Core, mit Feature Toggle
- Die aktuelle Logik, wohin man gelangt wenn man die URL `/` aufruft ist gemäss [routes.rb](https://github.com/hitobito/hitobito/blob/master/config/routes.rb#L12) der [DashboardController](https://github.com/hitobito/hitobito/blob/master/app/controllers/dashboard_controller.rb#L17)
- Um dieses Ziel je nach Feature Toggle zu überschreiben, könnte der Redirect (oder das Redirect-Ziel) im Fall eines eingeloggten Users in eine Methode ausgelagert werden.
- Der Controller akzeptiert auch JSON Requests. Dies ist aber nur in der deprecateten JSON API für eine noch länger deprecatete Version der Authentifizierung relevant. Daher muss kein grosser Effort darauf verwendet werden, dass das perfekt funktioniert, solange die [Specs](https://github.com/hitobito/hitobito/blob/master/spec/controllers/dashboard_controller_spec.rb#L24) dazu durchs refactoring nicht kaputt gehen.
- Um Texte in der Applikation dynamisch durch die Plattform-Admins bearbeitbar zu machen, haben wir die [CustomContents](https://github.com/hitobito/hitobito/blob/master/app/models/custom_content.rb). Diese können von Admins im globalen Einstellungen-Menü unter Texte bearbeitet werden, auch mehrsprachig und je nach Text mit Platzhaltern.

# ToDo

- [ ] Das Redirect-Ziel oder den ganzen Redirect im DashboardController in eine Methode auslagern
- [ ] Neuen Feature Toggle in den Settings anlegen, Default ausgeschaltet
- [ ] Neuen Feature Toggle im insieme Wagon einschalten
- [ ] Falls der Feature Toggle aktiviert ist, beim Redirect für eingeloggte User im DashboardController stattdessen eine neue Action `/dashboard` weiterleiten
- [ ] Neue Action in Routen, Controller und Views anlegen
- [ ] Neuen CustomContent anlegen (Beispiel für ist [hier](https://github.com/hitobito/hitobito/blob/master/db/seeds/custom_contents.rb))
- [ ] In der View die sprachlich passende Version des CustomContents anzeigen. Sicherstellen, dass HTML und insbesondere Links korrekt gerendert werden
- [ ] Specs für Redirect Methode schreiben
- [ ] Feature Spec für Dashboard View schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag im Wagon unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
Getestet.  👍
