### ISSUE TITLE
PERMISSIONS: Person löschen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_insieme#151]
Die Option zum definitiven Löschen der Personen ohne Rolle in den Listen «Ohne Rollen» der Regionalvereine sollen auch für die Rollen Geschäftsführung, Sekretariat und Adressverwaltung der Ebene Regionalvereine und Externe organisationen möglich sein. 

# Umsetzung: 
- Bei der Umgebung soll das Feature https://github.com/hitobito/hitobito/issues/2105 aktiviert werden.
  - Dabei werden die gleichen Parameter wie bei der PBS übernommen: 
    - Keine Kursteilnahme in den letzten 10 Jahren
    - Keine Lagerteilnahme in den letzten 10 Jahren
    - Gelöschte Felder beim Minimieren, analog PBS: https://github.com/hitobito/hitobito/issues/2106#issuecomment-1814421104
- Damit die entsprechenden Rollen auch die Berechtigung haben um die Rollen löschen zu können. Werden die folgenden neuen Berechtigungen vergeben:
  - Regionalverein
    - Geschäftsführung: [:layer_full, :contact_data]
    - Sekretariat: [:layer_full, :contact_data]
    - Adressverwaltung: [:layer_full, :contact_data]
  - Externe Organisation
    - Geschäftsführung: [:layer_full, :contact_data]
    - Sekretariat: [:layer_full, :contact_data]
    - Adressverwaltung: [:layer_full, :contact_data]

# Mockup
Ansicht als Admin:
![grafik](https://github.com/hitobito/hitobito_insieme/assets/100761305/dd072465-9cc8-454b-9bd4-bcb9c976b749)
Ansicht als Geschäftsführung:
![grafik](https://github.com/hitobito/hitobito_insieme/assets/100761305/81c653af-08db-429d-ad78-b1e52caf4555)

# Tech-Spec

- Das Bereinigen der Daten soll vereinfacht werden
- Das Feature "Datenlöschung/Minimierung" soll aktiviert werden
- nur einige Rollen sollen die entsprechenden Rechte bekommen

# ToDo

- [x] FeatureGate 'people.manual_deletion' aktivieren
- [x] Einstellungen analog zur PBS vornehmnen
- [x] Permission 'manually_delete_people' den genannten Rollen vergeben
- [x] Specs schreiben
- ~Kunde wegen Übersetzungen informieren~
- [ ] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

## Ergänzungen

- [x] FeatureGate 'people.cleanup_job' einbauen und deaktivieren
- [ ] hitobito/hitobito#2394
